name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.1
  json_annotation: ^4.9.0
  google_maps_flutter_android: ^2.14.14
  google_maps_flutter_platform_interface: ^2.11.1
  dio: ^5.8.0+1
  firebase_remote_config: ^5.4.2
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  dio_retry_plus: ^2.0.7
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  intl_utils: ^2.8.5

# 國際化設定 - 這應該是頂層配置，與 dependencies, dev_dependencies 同級
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  main_locale: zh_TW

# Flutter 相關配置
flutter:
  uses-material-design: true
  assets:
    - assets/images/
